global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - prometheus_alerts_rules.yml

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: sensors
    scrape_interval: 60s
    scrape_timeout: 50s
    static_configs:
      - targets: ['host.docker.internal:8000']
