{
 "title": "Air Quality Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sensors", "query": { "query": "label_values(sensor)" } }
  ]
 },
 "panels": [
  {
   "title": "CO(GT)",
   "type": "timeseries",
   "description": "True hourly averaged concentration CO in mg/m^3 (reference analyzer)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_co_gt_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT08S1_CO",
   "type": "timeseries",
   "description": "Tin oxide hourly averaged sensor response (nominally CO targeted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_pt08s1_co_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NMHC(GT)",
   "type": "timeseries",
   "description": "True hourly averaged overall Non Metanic HydroCarbons concentration in microg/m^3 (reference analyzer)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "air_quality_nmhc_gt_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT08S2_NMHC",
   "type": "timeseries",
   "description": "Titania hourly averaged sensor response (nominally NMHC targeted)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_pt08s2_nmhc_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NOX(GT)",
   "type": "timeseries",
   "description": "True hourly averaged NOx concentration in ppb (reference analyzer)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_nox_gt_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT08S3_NOX",
   "type": "timeseries",
   "description": "Tungsten oxide hourly averaged sensor response (nominally NOx targeted)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_pt08s3_nox_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "C6H6(GT)",
   "type": "timeseries",
   "description": "True hourly averaged Benzene concentration in microg/m^3 (reference analyzer)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_c6h6_gt_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT08S5_O3",
   "type": "timeseries",
   "description": "Indium oxide hourly averaged sensor response (nominally O3 targeted)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_pt08s5_o3_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NO2(GT)",
   "type": "timeseries",
   "description": "True hourly averaged NO2 concentration in microg/m^3 (reference analyzer)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_no2_gt_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT08S4_NO2",
   "type": "timeseries",
   "description": "Tungsten oxide hourly averaged sensor response (nominally NO2 targeted)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_pt08s4_no2_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "timeseries",
   "description": "Absolute Humidity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_ah_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "description": "Relative Humidity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "air_quality_rh_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in °C",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "air_quality_t_gauge{sensor=\"$sensors\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}